### ISSUE TITLE
Pre-competition launch to-do list 

### ISSUE THREAD

**Issue by jennazenk** [melonproject/ipfs-frontend#195]
Let's not launch competitions without checking/doing the following:

- [x] Update addresses of module contract on Setup page
- [x] Update T&Cs for conditions of use of Melon software
- [x] Update hash to be signed in Melon.js
- [x] Make sure Pricefeed updater account is well funded
- [x] Make sure Liquidity Provider account is well funded
